# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0464a5f0a937199f1b409a4a2735c1542520689e9dc3cb1cebc78abdefa62afe53f358fa497b0520020cd7065144c432f5afeefdf14a9e32732835df98b791a5

test:
  secret_key_base: 96e7f80719009fc37535709c4b2a23e778d55ad3d367398cccc846271cd96f68c2c7c4b5291d30eac94ab80939af620debe93544dcb5f4f6cd593ca7fad47404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
